# Generated by Django 5.1.5 on 2025-01-27 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_installments', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=240, null=True)),
                ('who_spent', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_card_name', to='cards.card')),
            ],
        ),
    ]
