# Generated by Django 5.1.5 on 2025-01-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=10)),
                ('due_date', models.DateField()),
                ('payment_date', models.DateField()),
            ],
        ),
    ]
